import { beforeEach, describe, expect, it, vi } from 'vitest';
const deferred=<T,>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{promise,resolve}};
const teams=new Map<number,ReturnType<typeof deferred<any>>>();
const mocks=vi.hoisted(()=>({getRooms:vi.fn<(...args:any[])=>Promise<any[]>>(async()=>[]),getAgents:vi.fn<(...args:any[])=>Promise<any[]>>(async()=>[]),getActivities:vi.fn<(...args:any[])=>Promise<any[]>>(async()=>[]),getTasks:vi.fn<(...args:any[])=>Promise<any[]>>(async()=>[]),getCurrentRun:vi.fn<(...args:any[])=>Promise<any>>(async()=>null),getRun:vi.fn<(...args:any[])=>Promise<any>>(async()=>null),getRunTimeline:vi.fn<(...args:any[])=>Promise<any[]>>(async()=>[]),getMessages:vi.fn<(...args:any[])=>Promise<any[]>>(async()=>[])}));
vi.mock('../api/client',()=>({getTeam:vi.fn((id:number)=>{const d=deferred<any>();teams.set(id,d);return d.promise}),...mocks,getTeams:vi.fn(async()=>[]),sendMessage:vi.fn(),wsUrl:vi.fn(()=> 'ws://test/ws/events.json'),activity:vi.fn(),task:vi.fn()}));
vi.mock('../realtime/socket',()=>({EventsSocket:class{connect(){} close(){}}}));
beforeEach(()=>{teams.clear();vi.clearAllMocks()});
describe('world reducer',()=>{
 it('applies planned native run event',async()=>{const {world}=await import('./world');world.applyEvent({type:'run_changed',teamId:1,run:{id:'r1',teamId:1,phase:'planning',progress:5}});expect(world.state.run?.id).toBe('r1');expect(world.state.run?.source).toBe('native')});
 it('updates publication',async()=>{const {world}=await import('./world');world.applyEvent({type:'publication_changed',teamId:1,runId:'r1',publication:{status:'published',url:'https://example.test/post'}});expect(world.state.run?.publication.status).toBe('published')});
 it('does not let an older loadTeam response overwrite the latest team',async()=>{const {world}=await import('./world');const first=world.loadTeam(1);const second=world.loadTeam(2);teams.get(2)!.resolve({id:2,name:'二院',i18n:{},enabled:true,config:{},questionRoomId:null});await second;teams.get(1)!.resolve({id:1,name:'一院',i18n:{},enabled:true,config:{},questionRoomId:null});await first;expect(world.state.team?.id).toBe(2);expect(world.state.loading).toBe(false)});
 it('loads archive execution data only from the run snapshot and timeline',async()=>{const {world}=await import('./world');mocks.getRun.mockResolvedValueOnce({id:'44',teamId:3,rootRoomId:7,phase:'completed',progress:100,question:'历史问题',finalAnswer:'结论',roomRuns:{7:{roomId:7,status:'completed',progress:100,currentAgentId:null,currentNpcStatus:'completed',activityLabel:'',completedTasks:1,totalTasks:1,lastActivityAt:null}},activeAgentIds:[],completedRoomIds:[7],publication:{status:'idle'},source:'native'});mocks.getRunTimeline.mockResolvedValueOnce([{id:1,roomId:7,senderId:9,senderName:'旧成员',content:'历史消息',sentAt:'2026-01-01',seq:1,immediate:false}]);const load=world.loadTeam(3,'44');teams.get(3)!.resolve({id:3,name:'三院',i18n:{},enabled:true,config:{},questionRoomId:8});await load;expect(world.state.rooms.map(r=>r.id)).toEqual([7]);expect(world.state.agents.map(a=>a.id)).toEqual([9]);expect(world.state.rooms[0].name).toBe('研究室 #7');expect(world.state.messages[7][0].content).toBe('历史消息');expect(world.state.tasks).toEqual([]);expect(world.state.activities).toEqual([]);expect(mocks.getRooms).not.toHaveBeenCalled();expect(mocks.getAgents).not.toHaveBeenCalled();expect(mocks.getMessages).not.toHaveBeenCalled();expect(mocks.getTasks).not.toHaveBeenCalled();expect(mocks.getActivities).not.toHaveBeenCalled()});
 it('keeps the existing publication when a run event omits it',async()=>{const {world}=await import('./world');world.applyEvent({type:'run_changed',teamId:3,run:{id:'44',teamId:3,phase:'publishing',progress:95,publication:{status:'publishing'}}});world.applyEvent({type:'run_changed',teamId:3,run:{id:'44',teamId:3,phase:'completed',progress:100}});expect(world.state.run?.publication).toEqual({status:'publishing'});expect(world.state.run?.progress).toBe(100)});
 it('ignores undefined values when merging run patches',async()=>{const {world}=await import('./world');world.applyEvent({type:'run_changed',teamId:3,run:{id:'44',teamId:3,finalAnswer:'新结论',publication:{status:'published',url:'https://example.test/p'}}});world.applyEvent({type:'run_changed',teamId:3,run:{id:'44',teamId:3,phase:'completed',progress:100,publication:undefined,finalAnswer:undefined}});expect(world.state.run?.finalAnswer).toBe('新结论');expect(world.state.run?.publication).toEqual({status:'published',url:'https://example.test/p'})});
});
