import type { Activity, Agent, I18n, Message, Room, RunSnapshot, Task, Team } from '../domain/types';
const BASE=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'');
const tokenKey='teamagent_token';
function url(path:string){return `${BASE}${path}`;}
async function json<T>(path:string, init:RequestInit={}):Promise<T>{
 const token=localStorage.getItem(tokenKey); const headers=new Headers(init.headers);
 if(!headers.has('Content-Type')) headers.set('Content-Type','application/json'); if(token) headers.set('Authorization',`Bearer ${token}`);
 const response=await fetch(url(path),{...init,headers});
 if(!response.ok){let message=`请求失败 (${response.status})`;try{const body=await response.json();message=body.error_desc||body.message||message;}catch{}throw new Error(message);} return response.json() as Promise<T>;
}
const i18n=(x:unknown):I18n => x && typeof x==='object' ? x as I18n : {};
export async function getTeams():Promise<Team[]>{const d=await json<{teams:any[]}>('/teams/list.json');return (d.teams||[]).map(x=>({id:Number(x.id),name:String(x.name||''),i18n:i18n(x.i18n),enabled:Boolean(x.enabled),config:x.config||{},createdAt:x.created_at,updatedAt:x.updated_at}));}
export async function getTeam(teamId:number):Promise<Team>{const x=await json<any>(`/teams/${teamId}.json`);return{id:Number(x.id),name:String(x.name||''),i18n:i18n(x.i18n),enabled:Boolean(x.enabled),config:x.config||{},createdAt:x.created_at,updatedAt:x.updated_at};}
export async function getRooms(teamId:number):Promise<Room[]>{const d=await json<{rooms:any[]}>(`/rooms/list.json?team_id=${teamId}`);return(d.rooms||[]).map(x=>{const r=x.gt_room||{};return{id:Number(r.id),teamId:Number(r.team_id||teamId),name:String(r.name||''),i18n:i18n(r.i18n),type:String(r.type||'group').toLowerCase()==='private'?'private':'group',state:String(x.state||'IDLE'),needScheduling:Boolean(x.need_scheduling),currentTurnAgentId:Number(x.current_turn_agent_id)>0?Number(x.current_turn_agent_id):null,agentIds:(x.agents||r.agent_ids||[]).map(Number).filter((n:number)=>n>0),tags:Array.isArray(r.tags)?r.tags:[],initialTopic:r.initial_topic??null};});}
export async function getAgents(teamId:number):Promise<Agent[]>{const d=await json<{agents:any[]}>(`/agents/list.json?team_id=${teamId}`);return(d.agents||[]).map(x=>({id:Number(x.id),teamId:Number(x.team_id||teamId),name:String(x.name||''),i18n:i18n(x.i18n),status:String(x.status||'idle').toLowerCase(),roleTemplateId:x.role_template_id,model:x.model,special:x.special}));}
function message(x:any,roomId:number):Message{return{id:x.db_id==null?null:Number(x.db_id),roomId,senderId:Number(x.sender_id),senderName:String(x.sender_display_name||''),content:String(x.content||''),sentAt:String(x.send_time||x.time||''),seq:x.seq==null?null:Number(x.seq),immediate:Boolean(x.insert_immediately)}}
export async function getMessages(roomId:number,limit=100):Promise<Message[]>{const d=await json<{messages:any[]}>(`/rooms/${roomId}/messages/list.json?limit=${limit}`);return(d.messages||[]).map(x=>message(x,roomId));}
export async function getActivities(teamId:number):Promise<Activity[]>{const d=await json<{activities:any[]}>(`/teams/${teamId}/activities.json`);return(d.activities||[]).map(activity);}
export function activity(x:any):Activity{return{id:Number(x.id||0),agentId:Number(x.agent_id||0),teamId:Number(x.team_id||0),roomId:x.room_id==null?(x.metadata?.room_id==null?null:Number(x.metadata.room_id)):Number(x.room_id),type:String(x.activity_type||'unknown').toLowerCase(),status:String(x.status||'started').toLowerCase(),title:String(x.title||''),detail:String(x.detail||x.error_message||''),startedAt:x.started_at||null,finishedAt:x.finished_at||null,metadata:x.metadata||{}}}
export async function getTasks(teamId:number):Promise<Task[]>{const d=await json<{tasks:any[]}>(`/teams/${teamId}/tasks.json?include_closed=true&limit=500`);return(d.tasks||[]).map(x=>task(x));}
export function task(x:any):Task{return{id:Number(x.id),teamId:Number(x.team_id),roomId:x.room_id==null?null:Number(x.room_id),assigneeId:Number(x.assignee_id||0),title:String(x.title||''),description:String(x.description||''),status:String(x.status||'TODO'),priority:String(x.priority||'NORMAL'),result:String(x.result||''),updatedAt:x.updated_at||null}}
export async function sendMessage(roomId:number,content:string,immediate=false):Promise<void>{await json(`/rooms/${roomId}/messages/send.json`,{method:'POST',body:JSON.stringify({content,insert_immediately:immediate})});}
export function normalizeRoomRuntime(x:any){return{roomId:Number(x.room_id??x.roomId),status:String(x.status||'waiting').toLowerCase(),progress:Number(x.progress_percent??x.progress??0),currentAgentId:Number(x.current_agent_id??x.currentAgentId)>0?Number(x.current_agent_id??x.currentAgentId):null,currentNpcStatus:String((x.current_activity??x.currentNpcStatus)||'idle').toLowerCase(),activityLabel:String((x.current_activity??x.activityLabel)||''),completedTasks:Number((x.completed_contributors??x.completedTasks)||0),totalTasks:Number((x.expected_contributors??x.totalTasks)||0),lastActivityAt:x.last_activity_at??x.lastActivityAt??null,error:x.error_message??x.error};}
export function normalizeRunSnapshot(payload:any):RunSnapshot|null{const r=payload?.run??payload;if(!r||!Number(r.id))return null;const roomList=Array.isArray(payload?.rooms)?payload.rooms:[];const roomRuns=Object.fromEntries(roomList.map((x:any)=>{const rr=normalizeRoomRuntime(x);return[rr.roomId,rr];}));return{id:String(r.id),teamId:Number(r.team_id??r.teamId),phase:String((r.status??r.phase)||'queued').toLowerCase() as RunSnapshot['phase'],progress:Number(r.progress_percent??r.progress??0),question:String((r.query??r.question)||''),finalAnswer:String((r.final_answer??r.finalAnswer)||''),roomRuns,activeAgentIds:roomList.map((x:any)=>Number(x.current_agent_id)).filter((id:number)=>id>0),completedRoomIds:roomList.filter((x:any)=>['COMPLETED','SKIPPED'].includes(String(x.status).toUpperCase())).map((x:any)=>Number(x.room_id)),publication:{status:String(r.blog_publish_status||'idle').toLowerCase() as RunSnapshot['publication']['status'],url:r.blog_post_url||undefined,error:r.error_message||undefined},startedAt:r.started_at,finishedAt:r.finished_at,source:'native'};}
export async function getRun(runId:string):Promise<RunSnapshot|null>{try{return normalizeRunSnapshot(await json<any>(`/runs/${encodeURIComponent(runId)}.json`));}catch{return null;}}
export async function getCurrentRun(teamId:number):Promise<RunSnapshot|null>{try{return normalizeRunSnapshot(await json<any>(`/runs/current.json?team_id=${teamId}`));}catch{return null;}}
export function wsUrl():string{if(BASE){const u=new URL(BASE);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/ws/events.json';u.search='';return u.toString();}return `${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws/events.json`;}
