<script setup lang="ts">
import { computed,onMounted,ref,watch,nextTick } from 'vue';import { useRoute } from 'vue-router';
import DialogueTimeline from '../components/DialogueTimeline.vue';import TaskSidebar from '../components/TaskSidebar.vue';import NpcAvatar from '../components/NpcAvatar.vue';import ProgressScroll from '../components/ProgressScroll.vue';import SpeakerTimeline from '../components/SpeakerTimeline.vue';import FileUploadButton from '../components/FileUploadButton.vue';import { world } from '../store/world';
const route=useRoute();const teamId=computed(()=>Number(route.params.teamId)),roomId=computed(()=>Number(route.params.roomId));const room=computed(()=>world.state.rooms.find(r=>r.id===roomId.value));const members=computed(()=>world.state.agents.filter(a=>room.value?.agentIds.includes(a.id)));const runtime=computed(()=>world.state.run?.roomRuns[roomId.value]);const messages=computed(()=>world.state.messages[roomId.value]||[]);const tasks=computed(()=>world.state.tasks.filter(t=>t.roomId===roomId.value));const activities=computed(()=>world.state.activities.filter(a=>a.roomId===roomId.value||room.value?.agentIds.includes(a.agentId)));const text=ref(''),immediate=ref(false),sending=ref(false),error=ref('');
async function load(){await world.loadTeam(teamId.value);await world.loadRoomMessages(roomId.value).catch(()=>{});}async function send(){if(!text.value.trim()||sending.value)return;sending.value=true;error.value='';try{await world.submitMessage(roomId.value,text.value.trim(),immediate.value);text.value='';immediate.value=false;}catch(e){error.value=e instanceof Error?e.message:'传讯失败';}finally{sending.value=false;}}
async function jumpToMessage(key:string){await nextTick();document.getElementById(key)?.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById(key)?.classList.add('timeline-focus');window.setTimeout(()=>document.getElementById(key)?.classList.remove('timeline-focus'),1800);}
async function uploaded(){await world.loadRoomMessages(roomId.value);}
onMounted(load);watch([teamId,roomId],load);
</script>
<template><div class="room-page"><header class="room-header"><RouterLink :to="{name:'team',params:{teamId}}">← 返回院落</RouterLink><div><small>研究室内景</small><h1>{{room?.name||'正在入室'}}</h1><p>{{runtime?.activityLabel||'静候差遣'}}</p></div><ProgressScroll :value="runtime?.progress||0" label="本室进度"/></header>
<section class="room-members panel" aria-label="本室参与大师"><header><b>本室诸贤</b><span>共 {{members.length}} 位大师参与本轮参详</span></header><div class="seating"><NpcAvatar v-for="agent in members" :key="agent.id" :agent="agent" :active="runtime?.currentAgentId===agent.id" :status="runtime?.currentAgentId===agent.id?runtime.currentNpcStatus:'idle'"/></div></section>
<SpeakerTimeline :messages="messages" :agents="members" @jump="jumpToMessage"/>
<div class="room-layout"><section class="discussion-panel panel"><header><h2>堂内对话</h2><span v-if="runtime?.currentAgentId">{{members.find(a=>a.id===runtime?.currentAgentId)?.name}} 当前执言</span></header><DialogueTimeline :messages="messages" :agents="members" :active-agent-id="runtime?.currentAgentId"/><form class="message-composer" @submit.prevent="send"><label for="message">向本室传讯</label><textarea id="message" v-model="text" rows="4" placeholder="输入问题或补充说明，支持 Markdown……" @keydown.ctrl.enter="send"></textarea><p v-if="error" class="error-text">{{error}}</p><div><FileUploadButton :room-id="roomId" :disabled="sending" @uploaded="uploaded"/><label class="check"><input v-model="immediate" type="checkbox"/> 趁本轮议论未歇，立即递入补充</label><small>Ctrl + Enter 发送</small><button :disabled="sending||!text.trim()">{{sending?'传讯中':'飞鸽传书'}}</button></div></form></section><TaskSidebar :tasks="tasks" :activities="activities" :agents="members" :initial-topic="room?.initialTopic" :question="world.state.run?.question" :room-status="runtime?.status"/></div></div>
</template>
