import { activity, task } from '../api/client';
import type { Message, NormalizedEvent, Publication, RoomRuntime, RunSnapshot } from '../domain/types';
export function normalizeEvent(raw:unknown):NormalizedEvent|null{
 if(!raw||typeof raw!=='object')return null;const x=raw as any;const type=String(x.event||x.type||'').toLowerCase();
 if(type==='message'){const r=x.gt_room||{};const roomId=Number(r.id||x.room_id),teamId=Number(r.team_id||x.team_id);if(!roomId||!teamId)return null;const m:Message={id:x.db_id==null?null:Number(x.db_id),roomId,senderId:Number(x.sender_id),senderName:String(x.sender_display_name||''),content:String(x.content||''),sentAt:String(x.time||x.send_time||new Date().toISOString()),seq:x.seq==null?null:Number(x.seq),immediate:Boolean(x.insert_immediately)};return{type,teamId,roomId,message:m};}
 if(type==='room_status'){const r=x.gt_room||{};if(!Number(r.id)||!Number(r.team_id))return null;return{type,teamId:Number(r.team_id),roomId:Number(r.id),state:String(x.state||'idle'),needScheduling:Boolean(x.need_scheduling),currentAgentId:Number(x.current_turn_agent_id)>0?Number(x.current_turn_agent_id):null};}
 if(type==='agent_status'){const a=x.gt_agent||{};if(!Number(a.id)||!Number(a.team_id))return null;return{type,teamId:Number(a.team_id),agentId:Number(a.id),status:String(x.status||'idle').toLowerCase()};}
 if(type==='agent_activity'){const a=activity(x.activity||x.data);return a.agentId&&a.teamId?{type,activity:a}:null;}
 if(type==='task_created'||type==='task_changed'){const t=task(x.task||{});return t.id&&t.teamId?{type:'task_changed',teamId:t.teamId,task:t}:null;}
 if(['message_changed','team_reloaded','room_added'].includes(type)){const room=x.gt_room||x.room||{};const teamId=Number(x.team_id||room.team_id);return teamId?{type:'reconcile',teamId,reason:type as 'message_changed'|'team_reloaded'|'room_added'}:null;}
 if(['run_created','run_phase_changed','run_progress_changed','run_changed','final_answer_completed'].includes(type)){const r=x.run||x.data||x;const id=String(r.id||r.run_id||x.run_id||'');const teamId=Number(r.team_id||x.team_id);if(!id||!teamId)return null;return{type:'run_changed',teamId,run:{id,teamId,phase:String(r.phase||r.status||'discussing').toLowerCase(),progress:Number(r.progress_percent??r.progress??0),question:String(r.query||r.question||''),finalAnswer:String(r.final_answer||''),publication:r.publication} as Partial<RunSnapshot>&{id:string}};}
 if(type==='room_run_changed'){const r=x.room_run||x.data||x;const teamId=Number(r.team_id||x.team_id),runId=String(r.run_id||x.run_id||'');if(!teamId||!runId||!Number(r.room_id))return null;const rr:RoomRuntime={roomId:Number(r.room_id),status:String(r.status||'waiting').toLowerCase() as RoomRuntime['status'],progress:Number(r.progress_percent??r.progress??0),currentAgentId:Number(r.current_agent_id)>0?Number(r.current_agent_id):null,currentNpcStatus:String(r.current_activity_type||'idle').toLowerCase() as RoomRuntime['currentNpcStatus'],activityLabel:String(r.activity_label||''),completedTasks:Number(r.completed_contributors||0),totalTasks:Number(r.expected_contributors||0),lastActivityAt:r.last_activity_at||null,error:r.error_message};return{type,teamId,runId,roomRuntime:rr};}
 if(type==='blog_publish_changed'){const teamId=Number(x.team_id),runId=String(x.run_id||'');if(!teamId||!runId)return null;const p:Publication={status:String(x.status||'pending').toLowerCase() as Publication['status'],url:x.post_url,error:x.error_message};return{type:'publication_changed',teamId,runId,publication:p};}
 return null;
}
