import { describe, expect, it } from 'vitest';
import { normalizeEvent } from './events';
describe('event normalizer',()=>{
 it('normalizes legacy room status',()=>{expect(normalizeEvent({event:'room_status',gt_room:{id:2,team_id:1},state:'SCHEDULING',need_scheduling:true,current_turn_agent_id:8})).toEqual({type:'room_status',teamId:1,roomId:2,state:'SCHEDULING',needScheduling:true,currentAgentId:8})});
 it('normalizes planned run events',()=>{const e=normalizeEvent({event:'run_progress_changed',run_id:99,team_id:1,phase:'DISCUSSING',progress_percent:42});expect(e?.type).toBe('run_changed');if(e?.type==='run_changed')expect(e.run.progress).toBe(42)});
 it.each(['message_changed','team_reloaded','room_added'] as const)('routes %s through reconcile',reason=>{expect(normalizeEvent({event:reason,team_id:7})).toEqual({type:'reconcile',teamId:7,reason})});
 it('derives reconcile team from room payload',()=>expect(normalizeEvent({event:'message_changed',gt_room:{id:2,team_id:9}})).toEqual({type:'reconcile',teamId:9,reason:'message_changed'}));
 it('rejects malformed events',()=>expect(normalizeEvent({event:'room_status'})).toBeNull());
 it('omits publication from run events that do not carry one',()=>{const e=normalizeEvent({event:'run_progress_changed',run:{id:5,team_id:1,status:'DISCUSSING',progress_percent:40}});expect(e?.type).toBe('run_changed');if(e?.type==='run_changed')expect('publication' in e.run).toBe(false)});
 it('derives publication from blog publish fields on run events',()=>{const e=normalizeEvent({event:'run_changed',run:{id:5,team_id:1,status:'COMPLETED',progress_percent:100,blog_publish_status:'PUBLISHED',blog_post_url:'https://example.test/post'}});if(e?.type==='run_changed')expect(e.run.publication).toMatchObject({status:'published',url:'https://example.test/post'})});
 it('maps room run npc status and label from current_activity',()=>{const e=normalizeEvent({event:'room_run_changed',run_id:9,room_run:{run_id:9,team_id:1,room_id:4,status:'DISCUSSING',progress_percent:50,current_agent_id:72,current_activity:'THINKING'}});if(e?.type==='room_run_changed'){expect(e.roomRuntime.currentNpcStatus).toBe('thinking');expect(e.roomRuntime.activityLabel).toBe('THINKING')}});
 it('falls back to idle when a room run carries no current activity',()=>{const e=normalizeEvent({event:'room_run_changed',run_id:9,room_run:{run_id:9,team_id:1,room_id:4,status:'COMPLETED',current_activity:null}});if(e?.type==='room_run_changed'){expect(e.roomRuntime.currentNpcStatus).toBe('idle');expect(e.roomRuntime.activityLabel).toBe('')}});
 it('normalizes blog publish updates that carry a team id',()=>{const e=normalizeEvent({event:'blog_publish_changed',team_id:1,run_id:9,status:'PUBLISHED',post_id:'p1',post_url:'https://example.test/post',error_message:null});expect(e).toEqual({type:'publication_changed',teamId:1,runId:'9',publication:{status:'published',url:'https://example.test/post'}})});
 it('tolerates blog publish updates without a team id',()=>{expect(normalizeEvent({event:'blog_publish_changed',run_id:9,status:'PUBLISHED'})).toBeNull()});
 it('maps retrying blog publish states to idle',()=>{const e=normalizeEvent({event:'blog_publish_changed',team_id:1,run_id:9,status:'RETRY_WAITING'});if(e?.type==='publication_changed')expect(e.publication.status).toBe('idle')});
});
